### ISSUE TITLE
Does this project has a py3 version?

### ISSUE THREAD

**Issue by DerekGrant** [szagoruyko/wide-residual-networks#40]
I try to convert this project to py3 version, it's a real good project, hopeful. But I still have a small problem didn't solve. I just can use one GPU now, and I meet a problem I want to use multiple, following is error info:
```
python main.py --save ./logs/resnet_$RANDOM$RANDOM --depth 28 --width 10 --ngpu 2 --gpu_id 0,1
```

```
Total number of parameters: 36554836
  0%|                                                   | 0/391 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 224, in <module>
    main()
  File "main.py", line 220, in main
    engine.train(h, train_loader, opt.epochs, optimizer)
  File "/home/xianbin/anaconda3/lib/python3.5/site-packages/torchnet-0.0.1-py3.5.egg/torchnet/engine/engine.py", line 39, in train
  File "/home/xianbin/anaconda3/lib/python3.5/site-packages/torch/optim/sgd.py", line 72, in step
    loss = closure()
  File "/home/xianbin/anaconda3/lib/python3.5/site-packages/torchnet-0.0.1-py3.5.egg/torchnet/engine/engine.py", line 28, in closure
  File "main.py", line 150, in h
    y = data_parallel(f, inputs, params, stats, sample[2], np.arange(opt.ngpu))
  File "/home/xianbin/PhD/CIFAR100/utils.py", line 52, in data_parallel
    params_replicas = replicate(params, lambda x: Broadcast(device_ids)(x))
  File "/home/xianbin/PhD/CIFAR100/utils.py", line 48, in replicate
    for i,u in enumerate(g(v)):
  File "/home/xianbin/PhD/CIFAR100/utils.py", line 52, in <lambda>
    params_replicas = replicate(params, lambda x: Broadcast(device_ids)(x))
  File "/home/xianbin/anaconda3/lib/python3.5/site-packages/torch/nn/parallel/_functions.py", line 19, in forward
    outputs = comm.broadcast_coalesced(inputs, self.target_gpus)
  File "/home/xianbin/anaconda3/lib/python3.5/site-packages/torch/cuda/comm.py", line 54, in broadcast_coalesced
    results = broadcast(_flatten_tensors(chunk), devices)
  File "/home/xianbin/anaconda3/lib/python3.5/site-packages/torch/cuda/comm.py", line 22, in broadcast
    with torch.cuda.device(device):
  File "/home/xianbin/anaconda3/lib/python3.5/site-packages/torch/cuda/__init__.py", line 128, in __enter__
    torch._C._cuda_setDevice(self.idx)
RuntimeError: invalid argument to setDevice
```

**Comment by szagoruyko** [comment]
@DerekGrant I fixed https://github.com/szagoruyko/wide-residual-networks/commit/4ed82e03d234a9a5fdbae71ff258b95a18e4956e and reproduced your error for a moment, but then it mysteriously started working. Can you try again with `python -m ipdb` flag?

**Comment by szagoruyko** [comment]
includes py3 support now.
